/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.jdbc;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Application {
    // Нужно указывать базовое исключение,
    // потому что выполнение запросов может привести к исключениям
    public static void main(String[] args) throws SQLException {
        // Создаем соединение с базой в памяти
        // База создается прямо во время выполнения этой строчки
        // Здесь hexlet_test — это имя базы данных
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test")) {

            var sql = "CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255), phone VARCHAR(255))";
            // Чтобы выполнить запрос, создадим объект statement
            try (var statement = conn.createStatement()) {
                statement.execute(sql);
            }

            var sql2 = "INSERT INTO users (username, phone) VALUES (?, ?)";
            try (var preparedStatement = conn.prepareStatement(sql2, Statement.RETURN_GENERATED_KEYS)) {
                
                
                preparedStatement.setString(1, "Tommy");
                preparedStatement.setString(2, "123456789");
                preparedStatement.executeUpdate();
                var generatedKeys = preparedStatement.getGeneratedKeys(); 
                if (generatedKeys.next()) {
                    System.out.println(generatedKeys.getLong(1));
                } else {
                    throw new SQLException("DB have not returned an ID after saving the entity");
                }
                
                preparedStatement.setString(1, "Vanya");
                preparedStatement.setString(2, "89172341276");
                preparedStatement.executeUpdate();
                var generatedKeys1 = preparedStatement.getGeneratedKeys();
                if (generatedKeys1.next()) {
                    System.out.println(generatedKeys1.getLong(1));
                } else {
                    throw new SQLException("DB have not returned an ID after saving the entity");
                }
                
                preparedStatement.setString(1, "Marya");
                preparedStatement.setString(2, "44444444");
                preparedStatement.executeUpdate();
                var generatedKeys2 = preparedStatement.getGeneratedKeys();
                if (generatedKeys2.next()) {
                    System.out.println(generatedKeys2.getLong(1));
                } else {
                    throw new SQLException("DB have not returned an ID after saving the entity");
                }
            }
            var sql3 = "DELETE FROM users WHERE username = ?";
            try (var preparedStatement1 = conn.prepareStatement(sql3)) {
                preparedStatement1.setString(1, "Marya");
                preparedStatement1.executeUpdate();
            }


            var sql4 = "SELECT * FROM users";
            try (var statement4 = conn.createStatement()) {
                // Здесь вы видите указатель на набор данных в памяти СУБД
                var resultSet = statement4.executeQuery(sql4);
                // Набор данных — это итератор
                // Мы перемещаемся по нему с помощью next() и каждый раз получаем новые значения
                while (resultSet.next()) {
                    System.out.print(resultSet.getString("username") + " ");
                    System.out.println(resultSet.getString("phone"));
                }
            }
        }
    }
}