/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Application {
    // Нужно указывать базовое исключение,
    // потому что выполнение запросов может привести к исключениям
    public static void main(String[] args) throws SQLException {
        // Создаем соединение с базой в памяти
        // База создается прямо во время выполнения этой строчки
        // Здесь hexlet_test — это имя базы данных
        try (Connection conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test")) {

            var sql = "CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255), phone VARCHAR(255))";
            // Чтобы выполнить запрос, создадим объект statement
            try (var statement = conn.createStatement()) {
                statement.execute(sql);
            }

            var user = new User("Tommy", "123456789");
            var user1 = new User("Vanya", "89172341276");
            var user2 = new User("Marya", "44444444");

            var userDao = new UserDAO(conn);
            userDao.save(user);
            userDao.save(user1);
            userDao.save(user2);
            var index = 3L;
            System.out.println(userDao.find(index).toString());
            userDao.delete(index);
            System.out.println(userDao.find(index).toString());

            var sql4 = "SELECT * FROM users";
            try (var statement4 = conn.createStatement()) {
                // Здесь вы видите указатель на набор данных в памяти СУБД
                var resultSet = statement4.executeQuery(sql4);
                // Набор данных — это итератор
                // Мы перемещаемся по нему с помощью next() и каждый раз получаем новые значения
                while (resultSet.next()) {
                    System.out.print(resultSet.getString("username") + " ");
                    System.out.println(resultSet.getString("phone"));
                }
            }
        }
    }
}